
#args for Guangzhou dataset

train:
  epochs: 3
  batch_size: 4
  lr: 3.0e-4

diffusion:
  layers: 2
  channels: 256
  nheads: 8
  diffusion_embedding_dim: 64 # the embedding dimension for diffusion steps
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 1000
  schedule: "linear"

model:
  device: "cuda:0"
  timeemb: 32
  featureemb: 32
  missing_pattern: "RM"
  missing_rate: 0.3
  BM_block_window_length: 6
  sequence_length: 18
  toddim: 144
  dowemb: 16
  todemb: 16
  save_folder: ""