
#args for Guangzhou dataset

train:
  epochs: 200
  batch_size: 16
  lr: 2.0e-3

diffusion:
  layers: 4
  channels: 128
  nheads: 8
  diffusion_embedding_dim: 64 # the embedding dimension for diffusion steps
  beta_start: 0.0001
  beta_end: 0.2
  num_steps: 100
  schedule: "quad"

model:
  device: "cuda:0"
  timeemb: 64
  featureemb: 128
  missing_pattern: "RM"
  missing_rate: 0.3
  BM_block_window_length: 6
  sequence_length: 18
  toddim: 144
  dowemb: 16
  todemb: 16
  save_folder: ""