
#args for Guangzhou dataset

train:
  epochs: 5
  batch_size: 4
  lr: 3.0e-3

diffusion:
  layers: 2
  channels: 32
  nheads: 4
  diffusion_embedding_dim: 32 # the embedding dimension for diffusion steps
  beta_start: 0.0001
  beta_end: 0.2
  num_steps: 100
  schedule: "quad"

model:
  device: "cuda:1"
  timeemb: 32
  featureemb: 32
  missing_pattern: "RM"
  missing_rate: 0.3
  BM_block_window_length: 6
  sequence_length: 18
  toddim: 144
  dowemb: 16
  todemb: 16
  save_folder: ""