
#args for Guangzhou dataset

train:
  epochs: 400
  batch_size: 2
  lr: 3.0e-4
  
diffusion:
  layers: 2
  channels: 256
  nheads: 4
  diffusion_embedding_dim: 32
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 1000
  schedule: "linear"

model:
  device: "cuda:0"
  timeemb: 16
  featureemb: 32
  missing_pattern: "RM"
  missing_rate: 0.3
  BM_block_window_length: 12
  sequence_length: 24
  toddim: 108
  dowemb: 16
  todemb: 16
  save_folder: ""