
# When num_steps is small, beta_end should be large, e.g., num_steps=100, beta_end=0.2
# vice versa, e.g., num_steps=1000, beta_end=0.002

train:
  epochs: 1000
  batch_size: 8
  lr: 3.0e-3
  nsample: 100
  test_ratio: 0.05
  
diffusion:
  layers: 2
  channels: 64
  nheads: 4
  diffusion_embedding_dim: 32
  beta_start: 0.0001
  beta_end: 0.2
  num_steps: 100
  schedule: "quad"

model:
  device: "cuda:0"
  timeemb: 32
  featureemb: 64
  missing_pattern: "RSM"
  missing_rate: 0.3
  sequence_length: 18
  toddim: 288
  dowemb: 32
  todemb: 32
  save_folder: ""
  sampling_shrink_interval: 4