
#args for Guangzhou dataset

train:
  epochs: 1000
  batch_size: 8
  lr: 3.0e-3
  
diffusion:
  layers: 2
  channels: 64
  nheads: 4
  diffusion_embedding_dim: 32
  beta_start: 0.0001
  beta_end: 0.2
  num_steps: 100
  schedule: "quad"

model:
  device: "cuda:0"
  timeemb: 32
  featureemb: 32
  missing_pattern: "NM"
  missing_rate: 0.7
  BM_block_window_length: 12
  sequence_length: 24
  toddim: 288
  dowemb: 32
  todemb: 32
  save_folder: ""