
#args for Guangzhou dataset

train:
  epochs: 20
  batch_size: 4
  lr: 3.0e-4
  
diffusion:
  layers: 2
  channels: 256
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 1000
  schedule: "linear"

model:
  device: "cuda:0"
  timeemb: 32
  featureemb: 32
  missing_pattern: "RM"
  missing_rate: 0.7
  BM_block_window_length: 12
  sequence_length: 36
  toddim: 288
  dowemb: 32
  todemb: 32
  save_folder: ""