
#args for Guangzhou dataset

train:
  epochs: 400
  batch_size: 8
  lr: 3.0e-4
  
diffusion:
  layers: 4
  channels: 256
  nheads: 8
  diffusion_embedding_dim: 256
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"

model:
  device: "cuda:0"
  timeemb: 128
  featureemb: 128
  missing_pattern: "RM"
  missing_rate: 0.7
  BM_block_window_length: 12
  sequence_length: 24
  toddim: 288
  dowemb: 32
  todemb: 128